### ISSUE TITLE
Wrong Results

### ISSUE THREAD

**Issue by plgruener** [SkullCarverCoder/wc18-cli#2] opened 2018-06-27 11:05 UTC
Running
``$> wc18 --country=Russia``
yields

>TEAM: Russia
>GROUP: A
>SOONEST MATCH: Monday, 25. June 2018 04:00PM
>STATISTICS:
>    *Status: Eliminated
>    *Goals: 8
>    *Matches Won: 2
>    *Matches Lost: 0
>    Matches Tied: 0

Today is 2018-06-27, so Russia
- has already played 3 matches (all present with ``--allmatches=True``)
- hast lost 1 match
- is not eliminated, but second of its group
- the next match is on 2018-07-01

**Comment by SkullCarverCoder** [comment] 2018-06-27 22:36
Fixed on 6c66d50a956ff137ca0cef903d6251459cd1dee7 , also about the date it actually works like this : 

If the match hapenned 2 days ago but it's 3 days away from the next match it'll take the last match (the one 2 days ago) when the amount of days away for the match is less than the days ago from the last match , it's printed , so the logic is "OK" given that it states (Soonest match) not Next Match. 

I hope I helped you and that the issue is resolved

**Closed as completed by SkullCarverCoder** 2018-06-27 22:36 UTC
